### ISSUE TITLE
Get 3 points like ...

### ISSUE THREAD

**Issue by naimbic** [Crocoblock/jet-engine-trim-callback#1]
Hello, i got 3 points when i choose trip by characters, is there any thing to do with it?
thanks
![FireShot Capture 007 - Parents Listing – Experts Petite Enfance - www expertspetiteenfance com](https://user-images.githubusercontent.com/6326117/119203828-f1824900-ba8b-11eb-863e-52234822889e.png)

**Comment by naimbic** [comment]
to get first char i choose 4 character, i f i choose 1 i got nothing than 3 points...

**Comment by kaskad88** [comment]
merged with https://github.com/Crocoblock/jet-engine-trim-callback/issues/9
