### ISSUE TITLE
Make it compatible with Bricks Builder

### ISSUE THREAD

**Issue by vm-marketing** [Crocoblock/jet-engine-trim-callback#6]
Make it compatible with Bricks Builder.

When loading it in the ListingGrid construction, you don't have the option of how many characters/words to display.

please make it compatible with bricks builder.

**Comment by Rubenzella** [comment]
it works with me. Using the latest version available of JetEngine.

**Comment by kaskad88** [comment]
@vm-marketing https://tppr.me/Z1k3D
